"""add telegram states

Revision ID: f0fef33dde05
Revises: e824bf388a90
Create Date: 2026-06-04 18:19:50.053537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0fef33dde05'
down_revision: Union[str, Sequence[str], None] = 'e824bf388a90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_states',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telegram_states')
    # ### end Alembic commands ###
